-- seed.sql — How to seed the pothole_reports table with 5,000 synthetic
-- citizen reports, plus verification queries.
--
-- The CSV (pothole_reports.csv) is generated by quests/pothole-poet/seed/generator.py
-- and is already present in your Cloud Workstation's repo clone.
--
-- ──────────────────────────────────────────────────────────────────────────────
-- Primary path — psql \copy from your Cloud Workstation terminal
-- ──────────────────────────────────────────────────────────────────────────────
--
--   export PGPASSWORD='buildwithgemini2026'
--   psql "host=${ALLOYDB_PRIVATE_IP} user=postgres dbname=postgres sslmode=require" \
--     -c "\copy pothole_reports FROM '/home/user/quest/pothole-poet/seed/pothole_reports.csv' WITH (FORMAT csv, HEADER true, NULL '')"
--
-- Get ${ALLOYDB_PRIVATE_IP} from: AlloyDB → cluster → primary instance → Connect.
--
-- ──────────────────────────────────────────────────────────────────────────────
-- Fallback path — gcloud import from Cloud Storage
-- ──────────────────────────────────────────────────────────────────────────────
--
--   gcloud alloydb clusters import pothole-archive \
--     --region=europe-west1 \
--     --database=postgres \
--     --gcs-uri="gs://${PROJECT_ID}-seed/pothole_reports.csv" \
--     --import-type=CSV \
--     --table=pothole_reports
--
-- ──────────────────────────────────────────────────────────────────────────────
-- Verify (paste these into AlloyDB Studio after the import completes)
-- ──────────────────────────────────────────────────────────────────────────────

-- 1. Total rows.
SELECT count(*) AS total_rows FROM pothole_reports;
-- Expected: 5000

-- 2. Distribution by neighbourhood — should match the generator's targets.
SELECT neighbourhood, count(*) AS reports
FROM pothole_reports
GROUP BY neighbourhood
ORDER BY reports DESC;
-- Expected: 12 rows. Hisingen (800) at top, Lorensberg (100) at bottom.

-- 3. Sanity check — sample five reports with quotes.
SELECT neighbourhood, severity_iron_marks, swallowed_object, reporter_quote
FROM pothole_reports
ORDER BY random()
LIMIT 5;
-- Expected: real-looking citizen complaints. If you see "It contains weather."
-- you have a treasure.
